esphome:
  name: apollo-msr-1
  friendly_name: Apollo Multisensor Mk1 (MSR-1)
  comment: Apollo Multisensor Mk1 (MSR-1)
  name_add_mac_suffix: true
  on_boot:
  - priority: 900.0
    then:
      - lambda: |-
          id(radar_bluetooth).turn_off();
  - priority: 500
    then:
      - text_sensor.template.publish:
          id: apollo_firmware_version
          state: "${version}"

  project:
    name: "ApolloAutomation.MSR-1"
    version: "${version}"

  min_version: 2026.8.0
  
dashboard_import:
  package_import_url: github://ApolloAutomation/MSR-1/Integrations/ESPHome/MSR-1.yaml
  import_full_config: false

logger:

ota:
  - platform: esphome
    password: ${ota_password}
  - platform: http_request
    id: ota_managed

wifi:
  on_connect:
    - component.update: update_http_request
  power_save_mode: none
  ap:
    ssid: "Apollo MSR1 Hotspot"

captive_portal:

web_server:
  port: 80
  version: 3

safe_mode:

update:
  - platform: http_request
    id: update_http_request
    name: Firmware Update
    source: https://apolloautomation.github.io/MSR-1/firmware/manifest.json

packages:
  core: !include Core.yaml