name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - Integrations/ESPHome/MSR-1.yaml
          - Integrations/ESPHome/MSR-1_BLE.yaml
          - Integrations/ESPHome/MSR-1_Factory.yaml
        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v3.1.0
        with:
          yaml_file: ${{ matrix.file }}